/**
 * 경기 관리 페이지 Mock 데이터
 * Phase 2에서 Supabase API로 대체 예정
 */

import type { ManagedMatch } from './types';

export const MOCK_MANAGED_MATCHES: ManagedMatch[] = [
  {
    id: '1',
    type: 'guest',
    status: 'scheduled',
    teamName: '강남 썬더스',
    date: '2025. 01. 20 (월)',
    time: '19:00',
    location: '강남구민체육센터 농구장',
    locationUrl: 'https://map.kakao.com',
    approvalStatus: '확정',
    amount: 15000,
  },
  {
    id: '2',
    type: 'host',
    status: 'scheduled',
    teamName: '서초 호퍼스',
    date: '2025. 01. 22 (수)',
    time: '20:00',
    location: '서초구민체육센터 농구장',
    locationUrl: 'https://map.kakao.com',
    applicants: 8,
    vacancies: 2,
  },
  {
    id: '3',
    type: 'team',
    status: 'ongoing',
    teamName: '판교 드래곤즈',
    date: '2025. 01. 13 (월)',
    time: '18:30',
    location: '판교테크노밸리 체육관',
    locationUrl: 'https://map.kakao.com',
    participants: 12,
  },
  {
    id: '4',
    type: 'tournament',
    status: 'scheduled',
    teamName: '용산 매버릭스',
    date: '2025. 01. 25 (토)',
    time: '14:00',
    location: '올림픽공원 농구장',
    locationUrl: 'https://map.kakao.com',
    tournamentName: '2025 서울시 농구대회',
    round: '본선 16강',
  },
  {
    id: '5',
    type: 'guest',
    status: 'pending',
    teamName: '마포 윙스',
    date: '2025. 01. 18 (토)',
    time: '15:00',
    location: '마포구민체육센터',
    locationUrl: 'https://map.kakao.com',
    approvalStatus: '승인대기',
    amount: 20000,
  },
  {
    id: '6',
    type: 'host',
    status: 'ended',
    teamName: '강동 이글스',
    date: '2025. 01. 10 (금)',
    time: '19:30',
    location: '강동구민체육센터',
    locationUrl: 'https://map.kakao.com',
    applicants: 10,
    vacancies: 0,
  },
  {
    id: '7',
    type: 'guest',
    status: 'cancelled',
    teamName: '송파 파이어스',
    date: '2025. 01. 15 (수)',
    time: '20:00',
    location: '송파구민체육센터',
    locationUrl: 'https://map.kakao.com',
    approvalStatus: '취소됨',
    amount: 18000,
  },
  {
    id: '8',
    type: 'guest',
    status: 'rejected',
    teamName: '노원 스타즈',
    date: '2025. 01. 16 (목)',
    time: '19:00',
    location: '노원구민체육센터',
    locationUrl: 'https://map.kakao.com',
    approvalStatus: '승인거부',
    amount: 15000,
  },
  {
    id: '9',
    type: 'team',
    status: 'ended',
    teamName: '강서 피닉스',
    date: '2025. 01. 08 (수)',
    time: '20:00',
    location: '강서구민체육센터',
    locationUrl: 'https://map.kakao.com',
    participants: 10,
  },
  {
    id: '10',
    type: 'tournament',
    status: 'ended',
    teamName: '성북 레이더스',
    date: '2025. 01. 05 (일)',
    time: '13:00',
    location: '성북구민체육센터',
    locationUrl: 'https://map.kakao.com',
    tournamentName: '2024 겨울컵 농구대회',
    round: '예선',
  },
];
