#!/usr/bin/env python3
"""
Figma Component Importer for Draft Project

Figma Make에서 생성된 UI를 Draft 프로젝트 구조로 변환하는 스크립트

Usage:
    python3 scripts/import-figma-component.py \\
        --name "match-create-form" \\
        --source-file "/tmp/figma-sample/src/pages/HostCreateMatch.tsx" \\
        --category "form"
"""

import argparse
import os
import re
from datetime import datetime
from pathlib import Path
import yaml

# 프로젝트 루트 경로
PROJECT_ROOT = Path(__file__).parent.parent
REGISTRY_DIR = PROJECT_ROOT / "src" / "components" / "registry"


def create_component_directory(name: str) -> Path:
    """컴포넌트 디렉토리 생성"""
    component_dir = REGISTRY_DIR / name
    component_dir.mkdir(parents=True, exist_ok=True)
    return component_dir


def generate_metadata(name: str, category: str, source_url: str = "") -> dict:
    """metadata.yaml 생성"""
    return {
        "name": name,
        "category": category,
        "description": f"{name} component imported from Figma Make",
        "source": {
            "type": "figma",
            "url": source_url if source_url else "manual",
            "imported_at": datetime.now().isoformat()
        },
        "status": "draft",
        "tags": [],
        "keywords": [],
    }


def convert_figma_to_draft(source_code: str, component_name: str) -> str:
    """
    Figma Make 코드를 Draft 프로젝트 형식으로 변환

    변환 작업:
    1. React Router → Next.js App Router
    2. Import 경로 수정
    3. AUTO-GENERATED 헤더 추가
    """

    # AUTO-GENERATED 헤더
    header = f'''/**
 * 🤖 AUTO-GENERATED by import-figma-component
 * 생성일: {datetime.now().strftime("%Y-%m-%d")}
 * Agent: scripts/import-figma-component.py
 *
 * ⚠️ 이 파일은 Figma Make에서 자동 변환된 파일입니다.
 * 수동 수정 시 다음 import 실행 시 덮어쓰여질 수 있습니다.
 */

'''

    # useNavigate → useRouter 변환
    code = source_code.replace(
        "import { useNavigate } from 'react-router-dom';",
        "import { useRouter } from 'next/navigation';"
    )
    code = code.replace("useNavigate()", "useRouter()")
    code = code.replace("navigate(", "router.push(")

    # Import 경로 수정
    code = re.sub(
        r"from ['\"]@/components/ui/([^'\"]+)['\"]",
        r"from '@/components/ui/\1'",
        code
    )

    # BrowserRouter 제거
    code = re.sub(
        r"import \{ BrowserRouter[^}]*\} from 'react-router-dom';?\n?",
        "",
        code
    )

    return header + code


def main():
    parser = argparse.ArgumentParser(
        description="Import Figma Make component to Draft project"
    )
    parser.add_argument(
        "--name", "-n",
        required=True,
        help="Component name in kebab-case (e.g., match-create-form)"
    )
    parser.add_argument(
        "--source-file", "-s",
        required=True,
        help="Path to Figma Make source file"
    )
    parser.add_argument(
        "--category", "-c",
        default="other",
        help="Component category (form, list, card, etc.)"
    )
    parser.add_argument(
        "--source-url",
        default="",
        help="Original Figma design URL"
    )
    parser.add_argument(
        "--force",
        action="store_true",
        help="Overwrite existing component"
    )

    args = parser.parse_args()

    # 1. 컴포넌트 디렉토리 생성
    component_dir = create_component_directory(args.name)

    if (component_dir / "index.tsx").exists() and not args.force:
        print(f"❌ Component '{args.name}' already exists. Use --force to overwrite.")
        return 1

    # 2. 소스 파일 읽기
    source_path = Path(args.source_file)
    if not source_path.exists():
        print(f"❌ Source file not found: {args.source_file}")
        return 1

    with open(source_path, 'r', encoding='utf-8') as f:
        source_code = f.read()

    # 3. 코드 변환
    converted_code = convert_figma_to_draft(source_code, args.name)

    # 4. index.tsx 생성
    index_path = component_dir / "index.tsx"
    with open(index_path, 'w', encoding='utf-8') as f:
        f.write(converted_code)

    # 5. metadata.yaml 생성
    metadata = generate_metadata(args.name, args.category, args.source_url)
    metadata_path = component_dir / "metadata.yaml"
    with open(metadata_path, 'w', encoding='utf-8') as f:
        yaml.dump(metadata, f, default_flow_style=False, allow_unicode=True)

    # 6. README.md 생성
    readme_content = f"""# {args.name}

**Category**: {args.category}
**Imported**: {datetime.now().strftime("%Y-%m-%d")}
**Source**: Figma Make

## Usage

\`\`\`tsx
import {args.name.replace('-', ' ').title().replace(' ', '')} from '@/components/registry/{args.name}';

<{args.name.replace('-', ' ').title().replace(' ', '')} />
\`\`\`

## Props

(TODO: Document props)
"""

    readme_path = component_dir / "README.md"
    with open(readme_path, 'w', encoding='utf-8') as f:
        f.write(readme_content)

    print(f"✅ Component '{args.name}' created successfully!")
    print(f"📁 Location: {component_dir.relative_to(PROJECT_ROOT)}")
    print(f"📝 Files created:")
    print(f"   - index.tsx")
    print(f"   - metadata.yaml")
    print(f"   - README.md")

    return 0


if __name__ == "__main__":
    exit(main())
